library(multcomp)
data(cholesterol)
head(cholesterol)
str(cholesterol)
summary(cholesterol)
aggregate(cholesterol$response, by = list(cholesterol$trt), FUN = sd)
fit <- aov(cholesterol$response ~ cholesterol$trt)
summary(fit)
TukeyHSD(fit)
